apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jesse

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - index.html
  name: hello-cm

patchesStrategicMerge:
  - patches/ingress.yaml
  - patches/index-override.yaml
  - patches/resources.yaml

images:
- name: probes-api
  newName: verbruggenjesse/webserver
  newTag: 1.0.0

resources:
- ../../base
