apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jesse

patchesStrategicMerge:
  - patches/resources.yaml

images:
- name: probes-api
  newName: verbruggenjesse/probes-api
  newTag: 1.0.0

resources:
- ../../base
